### ISSUE TITLE
Marshalls tmtools website cleanup

### ISSUE THREAD

**Issue by RD-X** [tanmay-rpatil/tm-web-scrape#2]
1. update readme
https://marshalls.org/tmtools/DCP_Hist.cgi?club=&dist=98&div=&area=&mon=0 as DCP_History_report_for_Div.csv
It shoudl be District not Div in csv file name
2.  get_clubs csv file needs to upended with date and source (http://www.marshalls.org/tmtools/getclubs.cgi?dist=98&Go=getclubs)
3. "title.csv" file needs to be checked in
4.  following errror needs to be addressed 
Traceback (most recent call last):
  File "./club-csv-cleanup.py", line 16, in <module>
    input_file = open('DCP_History_report_for_Club_1.csv', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'DCP_History_report_for_Club_1.csv'

**Comment by tanmay-rpatil** [comment]
3. ``` title.csv ``` has been added

**Comment by tanmay-rpatil** [comment]
fixed
