### ISSUE TITLE
  restructuring  output folder for ease of use 

### ISSUE THREAD

**Issue by RD-X** [tanmay-rpatil/tm-web-scrape#3]
1. Create two sub directories  inside output. Check-in updated directory structure 
	from-Marshalls
	from-TMI

2.  Once scripts executed files should be generated in following manner
     update scripts accordingly 
      /output /from-Marshalls
       *		DCP_History_report_for_Area.csv
	*		DCP_History_report_for_Club.csv
	*		DCP_History_report_for_District.csv
	*		DCP_History_report_for_Division.csv
	*		getclubs-details.csv
	 /output /from-TMI
	*		20_plus_members_ranking.csv
	*		Area_goal.csv
	*		Club_Performance.csv
	*		Club_goal.csv
	*		Clubs_need_coach.csv
	*		D98_Area_To_Do.csv
	*		Distinguished_Area_goals.csv
	*		Distinguished_Division_goals.csv
	*		District_Performance.csv
	*		District_goal_birds_eye.csv
	*		Division_Performance.csv
	*		Top10_Edu_Award.csv
	*		club_growth_ranking.csv 

3. update comment for output folder as output for tmi & Marshalls

**Comment by tanmay-rpatil** [comment]
fixed
