### ISSUE TITLE
Three tmi files are not getting copied in output/from-tmi folder

### ISSUE THREAD

**Issue by RD-X** [tanmay-rpatil/tm-web-scrape#5]
Three tmi files are not getting copied in output/from-tmi folder
-rw-r--r-- 1 Rajendra 197121 48431 Sep 14 19:19 Club_performance.csv
-rw-r--r-- 1 Rajendra 197121 40519 Sep 14 19:19 District_performance.csv
-rw-r--r-- 1 Rajendra 197121 53917 Sep 14 19:19 Division_performance.csv

**Comment by tanmay-rpatil** [comment]
added
